---
title: "Iteration and list document"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## List

You can put anything in a list

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE,TRUE, FALSE, TRUE,FALSE,FALSE),
  mat         = matrix(1:8, nrow = 2, ncol = 4),
  summary     = summary(rnorm(1000)))

l
```

```{r}
l$vec_numeric
l[[1]]   #show the first vector in the list, 从结果上，跟l$vec_numeric是一样的
l[[1]][1:3]
mean(l[["vec_numeric"]])
```

## For loop

Create a new list

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(30, 0, 5),
    c = rnorm(40, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)

```

```{r}
list_norms
```

Pause and get my old function

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)){
    stop("Input must be numeric")
  }
  
  if(length(x) < 3){
    stop("Inpur must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
 
}
```

I can apply that function to each list element

```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norms[[i]])
  
}
```

## Let's try map

```{r}
output = map(list_norms, mean_and_sd)   # 跟for loop效果一样，格式：map(input, function)
```

What if you want a different function..?

```{r}
output = map(list_norms, median)
output = map(list_norms, IQR)
```

