---
title: "Simulation"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1) # 放在这里意味着every time I knit,it's going to gave me the same result every single time
```


## Let's simulate something

I have a function

```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4) {
  
  sim_data = tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

I can `simulate` by running this line
```{r}
sim_mean_sd(30)
```

## Let's simulate a lot

Let's start with a for loop

```{r}
output = vector("list", 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(samp_size = 30)
}

sim_results = bind_rows(output)  # 不想要output是一个list，看起来不直观，用`bind_rows`变成data set
```

Let's use a loop function

```{r}
sim_results = 
  rerun(100, sim_mean_sd(samp_size = 30)) %>% 
  bind_rows()
```

Let's look at results

```{r}
sim_results %>% 
  ggplot(aes(x = mu_hat)) +
  geom_density()

sim_results %>% 
  ggplot(aes(x = sigma_hat)) +
  geom_density()

sim_results %>% 
  summarize(
    avg_samp_mean = mean(mu_hat),
    sd_samp_mean = sd(mu_hat)
  )

4/sqrt(30) # close to above result
```

## Let's try other sample sizes

```{r}
n_list = 
  list(
    "n = 30" = 30,
    "n = 60" = 60,
    "n = 120" = 120,
    "n = 240" = 240
  )

output = vector("list", length = 4)

output[[1]] = rerun(100, sim_mean_sd(samp_size = n_list[[1]])) %>% bind_rows()
output[[2]] = rerun(100, sim_mean_sd(samp_size = n_list[[2]])) %>% bind_rows()

for(i in 1:4) {
  output[[i]] = 
    rerun(100, sim_mean_sd(samp_size = n_list[[i]])) %>% 
    bind_rows()
}
```



```{r}
#`cache =`  means we don't want this result run again and again during knit, we want save this result in the corner and keep using them. 但是如果改了代码，这个chuck很容易break

tibble(
  sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~rerun(10,sim_mean_sd(.x)))
  ) %>% pull(output_lists)

tibble(
  sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~rerun(10,sim_mean_sd(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% pull(estimate_df)

sim_result = 
  tibble(
    sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~rerun(1000,sim_mean_sd(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)

```

do some data frame things

```{r}
sim_result %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat)) +
  geom_violin()
```


```{r}
sim_result %>%
  group_by(sample_size) %>% 
  summarize(
    avg_samp_mean = mean(mu_hat),
    sd_samp_mean = sd(mu_hat) 
  )
```

